### ISSUE TITLE
Support marshmallow 3.x

### ISSUE THREAD

**Issue by dsully** [SVilgelm/marshmallow-objects#20]
It'd be great to support Marshmallow's 3.x line.

I think all that needs to be done is checking if `.data` exists, which is not present in the 3.x releases.

Thanks!

**Comment by SVilgelm** [comment]
Hi @dsully,
Thank you so much. Please check #21

**Comment by dsully** [comment]
Awesome. Thanks for the quick turn-around. Could you release to pypi as well?

**Comment by SVilgelm** [comment]
Done. 1.0.8 version is uploaded to PyPi
