### ISSUE TITLE
Remove support for Marshmallow v2

### ISSUE THREAD

**Issue by SVilgelm** [SVilgelm/marshmallow-objects#22]
Marshmallow is moving to v3 and It's already have some incompatible features. I don't see any reasons to keep the hacks for compatibility with version 2.
So, I'm going to remove compatibility when Marshmallow releases a stable version 3.

**Comment by dsully** [comment]
+1

**Comment by Sytten** [comment]
Well this is it, v3 is released!

**Comment by lmignon** [comment]
@SVilgelm I need some features provided by marshmallow3 when instantiating a marshamallow object (ignore unknown fields).
Can I propose a PR to drop the support for v2?

**Comment by SVilgelm** [comment]
Fixed in #68

**Comment by SVilgelm** [comment]
Released in v2.0.0: https://pypi.org/project/marshmallow-objects/2.0.0/
