### ISSUE TITLE
How to invoke `__init__` method on a Model subclass?

### ISSUE THREAD

**Issue by lorencarvalho** [SVilgelm/marshmallow-objects#43]
Howdy 🙂 

From looking at ModelMeta's `__call__` method it seems that `__init__` is never called unless `__post_load__` is overridden when creating a Model object.

For example:

```
>>> from marshmallow_objects import Model, fields
>>> class Foo(Model):
...     test = fields.Bool()
...     def __init__(self, extra_data=None, *args, **kwargs):
...         self.extra_data = extra_data
>>> f = Foo(extra_data='123', test=True)
>>> f.test
True
>>> f.extra_data
>>> f = Foo(extra_data='123', test=True, __post_load__=True)
>>> f.extra_data
'123'
```

Is this intended? What would be the recommended way of achieving this without triggering the post_load code path in `ModelMeta.__call__`?

**Comment by SVilgelm** [comment]
Hmm, Why doesn't your code raise an exception? 
```python
f = Foo(extra_data='123', test=True)
>>> marshmallow.exceptions.ValidationError: {'extra_data': ['Unknown field.']}
```

**Comment by SVilgelm** [comment]
I think we need to play with `unknown` option, but I don't know how it works
