### ISSUE TITLE
Objects can't be copy.deepcopy()'d

### ISSUE THREAD

**Issue by dsully** [SVilgelm/marshmallow-objects#51]
Due to the use of:

```obj.__dump_lock__ = threading.RLock()```

In ModelMeta.__call__, an object cannot be copied with copy.deepcopy():

```TypeError: can't pickle _thread.RLock objects```

**Comment by dsully** [comment]
This is with Python 3.7

**Comment by SVilgelm** [comment]
The patch has been merged
