### ISSUE TITLE
Python support <=3.6 dropped with 2.0?

### ISSUE THREAD

**Issue by foxriver76** [SVilgelm/marshmallow-objects#70]
- is support for Python 3.5 and below dropped with 2.0?
- e.g. `File "/opt/iobroker/node_modules/iobroker.xbox/python_modules/lib/python3.5/site-packages/marshmallow_objects/models.py", line 209` this line is breaking due to trailing comma combined with * arguments

**Comment by SVilgelm** [comment]
I have fixed the issue and released new version 2.0.1

**Comment by foxriver76** [comment]
Thank you.
